# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Clipboard manager - stores text and images
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

